### ISSUE TITLE
Could not load type ...

### ISSUE THREAD

**Issue by 3KyNoX** [infinite-networks/InfiniteFormBundle#48]
Hello,

I got some problems making polycollection to work. 
InfiniteFormBundle is correctly installed.

I got a base contact entity (named bruno) whith inside a 'moyensComm' attribute set as ArrayCollection 

```php
// brunoBundle\Entity\Bruno.php

namespace brunoBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;
/**
 * Bruno
 */
class Bruno
{
    /**
     * @var integer
     */
    private $id;
    // ... other attributes
    
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $moyensComm;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->moyensComm = new ArrayCollection();
    }

    // getters & setters ...
}
```

Mapping for that class include a oneToMany relation to MoyenComm abstract entity described as follow

```yml
# brunoBundle\Resources\config\doctrine\Bruno.orm.yml
...
oneToMany:
        moyensComm:
            targetEntity: MoyenComm
            mappedBy: bruno
            cascade: ['persist', 'remove']
```

And here is the MoyenComm class 

```php
// brunoBundle\Entity\MoyenComm.php

namespace brunoBundle\Entity;

/**
 * MoyenComm
 */
abstract class MoyenComm
{
    /**
     * @var integer
     */
    protected $id;

    /**
     * @var \brunoBundle\Entity\Bruno
     */
    protected $bruno;

    // getters & setters ...
}
```

Which have inheritance ORM set to three subclasses (Telephone, Email & Adresse) and inversed map

```yml
# brunoBundle\Resources\config\doctrine\MoyenComm.orm.yml

brunoBundle\Entity\MoyenComm:
    type: entity
    table: null
    repositoryClass: brunoBundle\Entity\MoyenCommRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: integer
    discriminatorMap:
        1: Telephone
        2: Email
        3: Adresse
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        bruno:
            targetEntity: Bruno
            inversedBy: moyenComm
    fields:
        # fields here

    lifecycleCallbacks: {  }
```

Now I build my base form 

```php
// brunoBundle\Form\BrunoType.php

namespace brunoBundle\Form;

use brunoBundle\Form\Type\GenderType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class BrunoType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('text')
            ->add('textarea')
            ->add('email', 'email')
            ->add('entier')
            ->add('money', 'money')
            ->add('date')
            ->add('choice', new GenderType(), array(
                'expanded' => true,
                'multiple' => false
            ))
            ->add('moyensComm', 'infinite_form_polycollection',  array(
                'types' => array(
                    'brunobundle_moyencomm',
                    'brunobundle_telephone',
                    'brunobundle_email',
                    'brunobundle_adresse'
                ),
                'allow_add'    => true,
                'allow_delete' => true
            ))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'brunoBundle\Entity\Bruno'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'brunobundle_bruno';
    }
}
```

And here is the MoyenCommType

```php
// brunoBundle\Form\MoyenCommType.php

namespace brunoBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MoyenCommType extends AbstractType
{
    protected $dataClass = 'brunoBundle\Entity\MoyenComm';

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('_type', 'hidden', array(
            'data'   => $this->getName(),
            'mapped' => false
        ));
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class'  => $this->dataClass,
            'model_class' => $this->dataClass,
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'brunobundle_moyencomm';
    }
}
```

... and subclasses TelephoneType, EmailType, etc... that extends MoyenCommType.

The error I get is 

> Could not load type "brunobundle_moyencomm"
> 500 Internal Server Error - InvalidArgumentException

I checked the name exactly and all seem to be correct according to InfiniteFormBundle documentation.

Some help possible please ?

**Comment by 3KyNoX** [comment]
I get out of this error by settings my forms as service

```yml
  brunobundle_moyencomm:
    class: brunoBundle\Form\MoyenCommType
    tags:
      - { name: form.type }

  brunobundle_telephone:
      class: brunoBundle\Form\TelephoneType
      tags:
        - { name: form.type }

  brunobundle_email:
      class: brunoBundle\Form\EmailType
      tags:
        - { name: form.type }

  brunobundle_adresse:
      class: brunoBundle\Form\AdresseType
      tags:
        - { name: form.type }
```

But now it returns nothing

![](http://i.imgur.com/S3qC8Y1.png)

Any idea ?
