### ISSUE TITLE
SubType

### ISSUE THREAD

**Issue by 3KyNoX** [infinite-networks/InfiniteFormBundle#50]
Hello again,

I face currently another problem about defining "___sub-sub-type___".

If i re-take my last example available at https://github.com/infinite-networks/InfiniteFormBundle/issues/48, I got a main formType MoyenCommType that countains childrens : 

- TelephoneType
- EmailType
- AdresseType

Now I wish to extends TelephoneType -> MobileType

Then : 

- I created my Mobile entity (with only one property 'smsing' that means can sends sms)

```php
// brunoBundle/Entity/Mobile.php

namespace brunoBundle\Entity;

/**
 * Mobile
 */
class Mobile extends Telephone
{
    /**
     * @var boolean
     */
    protected $smsing;


    /**
     * Set smsing
     *
     * @param boolean $smsing
     *
     * @return Mobile
     */
    public function setSmsing($smsing)
    {
        $this->smsing = $smsing;

        return $this;
    }

    /**
     * Get smsing
     *
     * @return boolean
     */
    public function getSmsing()
    {
        return $this->smsing;
    }
}
```

- I setted my inheritance

```yml
#brunoBundle/Resources/config/doctrine/Telephone.orm.yml

brunoBundle\Entity\Telephone:
    type: entity
    table: null
    repositoryClass: brunoBundle\Entity\TelephoneRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: integer
    discriminatorMap:
        1: Mobile
    fields:
        numero:
            type: string
            length: 255

    lifecycleCallbacks: {  }
```

- Defined my new type with polycollection

```php
// brunoBundle/Form/ContactType
// ...
->add('moyensComm', 'infinite_form_polycollection', array(
    'types' => array(
        'brunobundle_moyencomm',
        'brunobundle_telephone',
        'brunobundle_email',
        'brunobundle_adresse',
        'brunobundle_mobile'
    ),
```

- And created my MobileType form : 

```php
// brunoBundle/Form/MobileType.php

namespace brunoBundle\Form;

use Symfony\Component\Form\FormBuilderInterface;

class MobileType extends TelephoneType
{
    protected $dataClass = 'brunoBundle\Entity\Mobile';

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('smsing')
        ;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'brunobundle_mobile';
    }
}
```

I finally updated database and added a first entry in the mobile table.

Now I try to get that value from my polycollection theme, prototype exists but that children appears nowhere from my dumps.

Any idea ?
