### ISSUE TITLE
Handling Polycollections errors

### ISSUE THREAD

**Issue by 3KyNoX** [infinite-networks/InfiniteFormBundle#51]
Hello !

I'm looking to manage errors with polycollections.
It's easy to manage normal fields or moyensComm validation using validation.yml file

```yml
brunoBundle\Entity\Contact:
    properties:
        moyensComm:
            - Count:
                min: 1
                max: 5
                minMessage: "Vous devez spécifier au moins un moyen de communication"
                maxMessage: "Vous ne pouvez ajouter plus de {{ limit }} moyen(s) de communication"
        text:
            - Length:
                min: 5
                max: 20
                minMessage: "Vous devez spécifier au minimum 5 caractères pour le champ 'Text'"
                maxMessage: "Vous êtes limités à {{ limit }} caractères pour le champ 'Text'"
```

But about Polycollections, not sure how to specify constraints.

Thanks for help.

**Comment by jmclean** [comment]
First you need to tell Symfony to apply validation rules to the entities in the `moyensComm` array:
```yaml
brunoBundle\Entity\Contact:
    properties:
        moyensComm:
            - Valid: ~
```
And then you can add validation rules for your derived classes:
```yaml
brunoBundle\Entity\Email:
    properties:
        email:
            - Email: ~
            - NotBlank: ~
```
You may also need to turn off `error_bubbling` on the polycollection to make some errors (like `Count` in your example) show up in the right place:
```php
        $builder
            ->add('moyensComm', 'infinite_form_polycollection', array(
                'error_bubbling' => false,
```
